services:
  postgres:
    image: postgres:13
    container_name: spring_security_postgres
    environment:
      POSTGRES_USER: security_user
      POSTGRES_PASSWORD: security_pass
      POSTGRES_DB: security_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
